export * from "./types";
export * from "./tools/registry";
export * from "./tools/builtin/calculator";
export * from "./tools/builtin/datetime";
export * from "./tools/builtin/read-file";
export * from "./tools/builtin/webSearch";
export * from "./tools/builtin/web-fetch";
export * from "./tools/builtin/github";
export * from "./tools/builtin/local-system";
export * from "./tools/builtin/executeCode";
export * from "./tools/builtin/visual-understanding";
export { visualUnderstandingTool } from "./tools/builtin/visual-understanding";
export * from "./tools/builtin/image-generation";
export { imageGenerationTool } from "./tools/builtin/image-generation";
export * from "./runtime";
export * from "./approvals";
export * from "./orchestrators";
export * from "./mcp/client";
export * from "./heterogeneous/types";
export * from "./heterogeneous/runner";

import { globalToolRegistry } from "./tools/registry";
import { calculator } from "./tools/builtin/calculator";
import { datetime } from "./tools/builtin/datetime";
import { readFileTool } from "./tools/builtin/read-file";
import { webSearch } from "./tools/builtin/webSearch";
import { webFetchTool } from "./tools/builtin/web-fetch";
import { githubRepoTool } from "./tools/builtin/github";
import { localSystemTool } from "./tools/builtin/local-system";
import { executeCodeTool } from "./tools/builtin/executeCode";
import { imageGenerationTool } from "./tools/builtin/image-generation";

// Register default tools
globalToolRegistry.register(calculator);
globalToolRegistry.register(datetime);
globalToolRegistry.register(readFileTool);
globalToolRegistry.register(webSearch);
globalToolRegistry.register(webFetchTool);
globalToolRegistry.register(githubRepoTool);
globalToolRegistry.register(localSystemTool);
globalToolRegistry.register(executeCodeTool);
globalToolRegistry.register(imageGenerationTool);
